function(target_use_clang_tidy target enable clang_config_path)
    if (NOT ${enable})
        return()
    endif()
    message(STATUS "${target} compiled with clang tidy")
    include(${clang_config_path})
    set(CLANG_TIDY_COMMAND "${CLANG}" "${CLANG_TIDY_CONFIG} ${CLANG_WARNING}")
    set_target_properties(${target} PROPERTIES CXX_CLANG_TIDY "${CLANG_TIDY_COMMAND}")
endfunction()